### ISSUE TITLE
Checksum?

### ISSUE THREAD

**Issue by nic** [AngelKitty/IDA7.0#5]
Official IDA Site:
<img width="1038" alt="official IDA site" src="https://user-images.githubusercontent.com/66042/60760217-1f7d5200-a008-11e9-88dc-a020d5c4eb05.png">

From this Github repository:
<img width="569" alt="From github" src="https://user-images.githubusercontent.com/66042/60760242-7c790800-a008-11e9-8710-2ea7d71abb21.png">

Why?
![18mq5r](https://user-images.githubusercontent.com/66042/60760252-ad593d00-a008-11e9-984e-71b9b0925b60.jpg)

**Comment by SavoryKittens** [comment]
I concur. Watch out people. 

Hex-Rays: d19d34bfc609e28cbfd92c1468c330d032130ec3
This Upload: b8d77cbcc3ca5b08ffaafcea3149e64bb0da7441

**Comment by lixiang123321** [comment]
i have the same problem.
linux sha1sum isnot the same with offical website.

**Comment by AngelKitty** [comment]
> Official IDA Site:
> <img alt="official IDA site" width="1038" src="https://user-images.githubusercontent.com/66042/60760217-1f7d5200-a008-11e9-88dc-a020d5c4eb05.png">
> 
> From this Github repository:
> <img alt="From github" width="569" src="https://user-images.githubusercontent.com/66042/60760242-7c790800-a008-11e9-8710-2ea7d71abb21.png">
> 
> Why?
> ![18mq5r](https://user-images.githubusercontent.com/66042/60760252-ad593d00-a008-11e9-984e-71b9b0925b60.jpg)

Thank you for your report this issue, It's right. These reasons may be due to the use of some download tools such as IDM or network instability. But I think network may be the main issue. Now I have corrected the shasum and re-uploaded it.

**Comment by AngelKitty** [comment]
@SavoryKittens @lixiang123321 Thank you for your report this issue, Now I'm already corrected the shasum and re-uploaded it.

**Comment by nic** [comment]
Now is correct! Thanks @AngelKitty
